DROP TABLE store_address
DROP TABLE customer_address;
DROP TABLE customer_phone;
DROP TABLE store_phone;
DROP TABLE phone;
DROP TABLE addresses;
DROP TABLE store;
DROP TABLE order_item;
DROP TABLE order_detail;
DROP TABLE wishlist;
DROP TABLE customer;
DROP TABLE variant_color;
DROP TABLE color;
DROP TABLE variant;
DROP TABLE gender;
DROP TABLE category;