version: "3.8"
services:
  nginx:
    container_name: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    networks:
      - pern-network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /usr/src/app/node_modules
      - ./client:/usr/src/app
    networks:
      - pern-network
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    networks:
      - pern-network
    depends_on:
      - postgres-tfr

  postgres-tfr:
    container_name: postgres-tfr
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    networks:
      - pern-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tfr
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./api/db/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql # creates database's tables.
      - ./api/db/functions.sql:/docker-entrypoint-initdb.d/functions.sql # creates database's functions.
      - ./api/db/insert.sql:/docker-entrypoint-initdb.d/insert.sql # inserts data into database's tables.

  pgadmin-tfr:
    container_name: pgadmin-tfr
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    networks:
      - pern-network
    depends_on:
      - postgres-tfr

networks:
  pern-network:
    driver: bridge

volumes:
  postgres-data:
    name: postgres-data
  client-environment:
    name: client-environment
