/**
 * Constantes que determina el tipo de accion en el ProductReducer
 */
export const TYPES = {
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  GET_TOTAL_PRODUCTS: "GET_TOTAL_PRODUCTS",
  GET_TOTAL_PRICE: "GET_TOTAL_PRICE",
  GET_WISHLIST: "GET_WISHLIST",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  ADD_PRODUCT_TO_BUY: "ADD_PRODUCT_TO_BUY",
  BUY_CART: "BUY_CART",
  CLEAR_LIST_OF_PRODUCTS_TO_BUY: "CLEAR_LIST_OF_PRODUCTS_TO_BUY",
  GET_MY_ORDERS: "GET_MY_ORDERS",
  REMOVE_AN_ORDER: "REMOVE_AN_ORDER",
  CREATE_INVOICE: "CREATE_INVOICE",
  RESET_PRODUCT_STATE: "RESET_PRODUCT_STATE",
};
